# Generated by Django 4.0.4 on 2022-08-31 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_dataset_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='sets',
            field=models.ManyToManyField(to='contact.dataset', verbose_name='datasets this measurement appears in'),
        ),
    ]
