# Generated by Django 4.0.4 on 2022-04-20 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('description', models.TextField()),
                ('writer_name', models.CharField(max_length=30)),
                ('about_writer', models.TextField()),
            ],
        ),
    ]
