# Generated by Django 4.0.4 on 2022-04-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_blogmodel_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='highlights',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='blog',
            name='about_writer',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(blank=True, default=None),
        ),
    ]
