# Generated by Django 4.0.4 on 2022-04-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_highlights_alter_blog_about_writer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='post',
            field=models.ImageField(default=None, upload_to='images'),
        ),
    ]
