# Generated by Django 4.0.4 on 2022-04-21 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='post',
        ),
    ]
