# Generated by Django 4.0.4 on 2022-04-22 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
