# Generated by Django 4.0.4 on 2022-04-25 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='post_image',
        ),
    ]
