# Generated by Django 4.0.4 on 2022-08-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_blog_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='rating',
            field=models.CharField(blank=True, choices=[('b', 'Bad'), ('a', 'Average'), ('e', 'Excellent')], max_length=1, null=True),
        ),
    ]
