# Generated by Django 4.0.4 on 2022-08-26 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_blog_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name_plural': 'Blogs'},
        ),
    ]
