# Generated by Django 4.0.4 on 2022-04-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profileimage',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images'),
        ),
    ]
