# Generated by Django 4.0.4 on 2022-04-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_profileimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profileimage',
            new_name='profile_image',
        ),
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
