# Generated by Django 4.0.4 on 2022-04-29 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'default_permissions': ('add', 'change', 'delete', 'view')},
        ),
    ]
