# Generated by Django 4.0.4 on 2022-08-24 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(to='pizzeria.topping'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='topping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_topping', to='pizzeria.topping'),
        ),
    ]
