# Generated by Django 4.0.4 on 2022-08-24 05:33

from django.db import migrations


def forward(apps, schema_editor):
    Pizza = apps.get_model("pizzeria", "Pizza")
    for pizza in Pizza.objects.all():
        pizza.toppings.add(pizza.topping)


class Migration(migrations.Migration):
    dependencies = [
        ('pizzeria', '0002_pizza_toppings_alter_pizza_topping'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
