# Generated by Django 4.0.4 on 2022-08-24 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0003_auto_20220824_0533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='topping',
        ),
    ]
