# Generated by Django 4.0.4 on 2022-08-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0004_remove_pizza_topping'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='is_soldout',
            field=models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True),
        ),
    ]
