# Generated by Django 4.0.4 on 2022-08-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0005_pizza_is_soldout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='is_soldout',
            field=models.IntegerField(blank=True, choices=[(1, 'Available'), (0, 'Soldout')], default=1, help_text='1->Available, 0->Soldout', null=True),
        ),
    ]
