# Generated by Django 4.0.4 on 2022-08-06 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inlineformset', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FamilyMember',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
