# Generated by Django 4.0.4 on 2022-08-06 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inlineformset', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectiontitle',
            name='collection',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='CollectionTitle',
        ),
    ]
