# Generated by Django 4.0.4 on 2022-04-26 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0002_likes_like_alter_likes_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='image_like',
        ),
    ]
