# Generated by Django 4.0.4 on 2022-05-12 10:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0003_remove_likes_image_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
